name: Update Fork

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  update-fork:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Trigger Repository Dispatch
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          https://github.com/face-less-world/test-repo-fork/dispatches \
          -d '{"event_type": "update-fork"}'
